### ISSUE TITLE
How to stop auto closing of window after execution of the RETURN statement?

### ISSUE THREAD

**Issue by gurditsbedi** [MontFerret/ferret#131]
I am developing my .fql script by trial and error. I am using browser mode with ferret.
What I want is that when RETURN statement is executed, the chrome window attached with the script should not get closed. 
example: steps:
1. I am logging inside a website.
2. INPUT username and password
3. CLICK login button.
4. RETURN TRUE is executed and the chrome window closes. ( unable to see what happens after logging in)

**Comment by ziflex** [comment]
@gurditsbedi hey, nice to hear that you are playing with Ferret!
What do you want to do with that open tab?
You can always to add ``WAIT(time)`` statement in order to inspect what happened on the screen.
But in general, closing an open tab is a part of the resource deallocation process and keeping it open would mean resource leakage.

**Comment by gurditsbedi** [comment]
Currently, I am in this loop.
1. Go to this page
2. Inspect element and make further additions to the script.

since page come one by one, if the tab gets closed I won't be able to inspect.

Again, I think if their is an option of keeping the window open even after the RETURN, it may be helpful in some cases.

**Comment by ziflex** [comment]
Just put ``WAIT(600000)`` in front of RETURN statement. It will put the process in sleep mode for 10 minutes.

**Comment by ziflex** [comment]
Feel free to re-open if you have more questions.
