### ISSUE TITLE
Can ferret catch the error of chrome process Termination and auto exit running ferret script?

### ISSUE THREAD

**Issue by kaixinbuyu** [MontFerret/ferret#304]
Ferret.exe ----exec.Command-----Chrome.exe

what if chrome.exe crashed or chrome tab page crashed?
I simulate chrome crash by sample close the chrome.exe process.
Then I receive a log of error log  message like "error":"cdp.DOM: ResolveNode: rpcc: the connection is closing".
But the ferret script is still running.
Can ferret catch the error of chrome process Termination and auto exit running ferret script?

**Comment by ziflex** [comment]
Hi @kaixinbuyu!
That's a good question. 
At this moment, there is no such mechanism in CLI version (you may try to cancel a context in embedded scenario) and in the driver's package.

But, this is something I was thinking about. I guess, the easiest way to fix it is returning an error which would terminate the execution instead of writing logs.

**Comment by kaixinbuyu** [comment]
there are many "low level" errors when communicating with headless-chrome,these errors can't throw out to ferret or cancel the context.

how about this:

cmd := exec.Command of Chrome.exe //cli.go
...
go func() {
    err := cmd.Wait()
    //wait end,so chrome process finished.
    cancel()  //cancel ctx
}
