### ISSUE TITLE
High and growing memory/cpu when using cdp

### ISSUE THREAD

**Issue by itmeze** [MontFerret/ferret#420]
**Describe the bug**
When running multiple request using cdp driver - memory grows fast, CPU goes to 100%. Each subsequent request executes slower. 
In the script below, first google.com loads in 1sec, after 10 requests, this goes to 2 sec, and so on, effectively reaching 6sec per google.com load time. 
Same behavior on local PC, as on ecs (aws).  

**To Reproduce**
1. Run chrome using: google-chrome --disable-gpu --headless --no-sandbox --remote-debugging-port=9222 --user-data-dir=/data --disable-dev-shm-usage
2. Run script
```
func main(){
        script := `
	FOR page IN 1..100
		LET doc = DOCUMENT("https://www.google.com", {
			driver: "cdp",
			userAgent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"
		})
		RETURN {page: page}
	`
	comp := compiler.New()
	program, err := comp.Compile(script)

	if err != nil {
		panic(err)
	}

	ctx := drivers.WithContext(context.Background(), cdp.NewDriver())
	ctx = drivers.WithContext(ctx, http.NewDriver(), drivers.AsDefault())

	program.Run(ctx, runtime.WithLogLevel(logging.DebugLevel))
}
```

**Expected behavior**
Complete in reasonable time frame, releasing resources under each loop exit

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10, Amazon Linux 2

**Comment by ziflex** [comment]
Hi, 
first of all, thank you for trying out Ferret and testing its performance!  👍
Second, could you tell me what version of Ferret you are using? 

There are several reasons why you are having high memory and cpu usage:
- On each iteration you are opening a new Chrome tab by creating a new CDP Document. It's not free.
- Each document has an event loop that tracks changes made to its DOM tree (there is a [fix](https://github.com/MontFerret/ferret/pull/402) in the master that decreased CPU usage and in the future releases I'm planning to provide an option to turn it off), which also has its own CPU penalty.
- The way how Ferret deals with "disposable" resources leads to the growth on every iteration. It just does not clean up resources after each iteration (when a scope is not active anymore) because of a lack of escape analysis (another thing to improve) and therefore, it waits until the program ends to free the resources (otherwise, if it cleans them on each iteration and a resource escapes the scope, you will get an error when you will use the resource outside)

**Comment by ziflex** [comment]
Typically, when you need to deal with a big amount of pages in a script, I recommend just to open an empty page and during iteration navigate it to a target page.
