### ISSUE TITLE
distributed

### ISSUE THREAD

**Issue by ghost** [MontFerret/ferret#62]
lots of servers block you if you make too many requests at a time.

So solution is either to put a wait in OR run the script from many cloud servers.
I like the 2nd option

It would mean that each one runs in a command and control fashion i think.
a central brain controls them all, telling them the exact next step, but each shares the same cookie etc for authenticated scraping.

Raising this as an idea...

**Comment by ziflex** [comment]
@this a good idea and I have plans to implement it. The only thing is that you need to setup a proxy server/load balancer on a such way that I nice a query calls a Chrome instance, all consequent requests should be redirected to the same Chrome instance.

For now, we you may try to set up a proxy settings in Chrome itself.

**Comment by gedw99** [comment]
I would not use a load balancer because you don't have enough control.

Instead use NATS to route messages. In a queue group you get a type of load balancing. The first one to take the message executes it and the others do nothing.

You can embed NATS into any golang program too, so nothing extra needed.
Kind of nice and easy.

That's sort of my gut instinct way to do it and make it really easy.

The really hard bit is to invent a loop key word in your DSL that indicates that it should be distributed. Each interaction of the loop would call a Ross on the NATS queue group.

If your currently using golang channels then it's very easy to hook into NATS at that level btw too. So it is essentially then doing concurrency over the network of NATS ubscribers, rather then local golang threads / goroutines 
So that might also be an easy way to distribute.

Also if a server tries to run the scrape but fails, then it can message you back and you can just ask another to do it.

Just brainstorming the architecture. Have not had a chance to dig into your code yet though..

**Comment by ziflex** [comment]
@gedw99 sounds interesting, I will look into NATS more deeply later on.
The only thing that I would not like to do is to change DSL for that - any query should be executed in the same manner on both single Chrome instance and a cluster. There should not be any differences in the query itself.
As an option we may add some extra [options](https://github.com/MontFerret/ferret/blob/master/pkg/runtime/options.go) you can run a program with, in order to instruct underlying transport how to handle requests if needed.
But by the end of the day it depends on whether it's possible to that with Chrome DevTool Protocol (and [underlying client](https://github.com/mafredri/cdp))

**Comment by kaixinbuyu** [comment]
how do you think of browserless's blog about "4. Parallelize with browsers, not pages"
[https://docs.browserless.io/blog/2018/06/04/puppeteer-best-practices.html](url)
I have many detail-page urls to be crawled by chrome.the case is the same as a distributed,clustered headless chrome.

The solution before I read the blog is:
opening 10 chrome.exe,
each chrome.exe open fixed 10-chrome pages,
and each page crawl <- an url array[1000+].

browserless's suggestion is on the contrary:
each detail-url open a chrome.exe,a chrome page.


`4. Parallelize with browsers, not pages
Since we've determined that it's not good to run a browser, and that we should only run one when absolutely necessary, the next best-practice is to run only one session through each browser. While you actually might save some overhead by parallelizing work through pages, if one page crashes it can bring down the entire browser with it. That, plus each page isn't guaranteed to be totally clean (cookies and storage might bleed-through as seen here).

Instead of this:

import puppeteer from 'puppeteer';

// Launch one browser and capture the promise
const launch = puppeteer.launch();

const runJob = async (url) {
    // Re-use the browser here
    const browser = await launch;
    const page = await browser.newPage();
    await page.goto(url);
    const title = await page.title();

    browser.close();

    return title;
};
Do this:

import puppeteer from 'puppeteer';

const runJob = async (url) {
    // Launch a clean browser for every "job"
    const browser = puppeteer.launch();
    const page = await browser.newPage();
    await page.goto(url);
    const title = await page.title();

    browser.close();

    return title;
};
Each new browser instance gets a clean --user-data-dir (unless otherwise specified), which means it's treated as a fresh session entirely. If Chrome crashes for whatever reason, it won't bring down any other sessions that are happening as well.`

**Comment by ziflex** [comment]
I think it's up to you. I would go with tabs approach because it's more resource efficient, but if you start experiencing Chrome crashes, then I would switch to 1 instance per query.

**Comment by kaixinbuyu** [comment]
how about this?
lunch 10 remote chrome process (or remote docker container with chrome) just by **ssh**,
then ferret(only one ferret) do not need much change,
the deployment is sample as well,only one ferret installed on local machine,only chrome installed on remote machines.

**Comment by ziflex** [comment]
This is out of scope of this library.
Distributed execution can be done with other dedicated solutions.
